#!/usr/bin/env python3
"""
Simple FinOps cost report for the GPU ML Platform.
This script is designed to be run by GitHub Actions on a schedule.
It uses boto3 (Cost Explorer) to pull recent costs and highlights GPU-related spend.
"""

import boto3
from datetime import datetime, timedelta
from collections import defaultdict
import sys

def get_cost_and_usage(client, start, end):
    """Fetch cost and usage data grouped by service and usage type."""
    try:
        response = client.get_cost_and_usage(
            TimePeriod={
                'Start': start,
                'End': end
            },
            Granularity='DAILY',
            Metrics=['UnblendedCost'],
            GroupBy=[
                {'Type': 'DIMENSION', 'Key': 'SERVICE'},
                {'Type': 'DIMENSION', 'Key': 'USAGE_TYPE'}
            ]
        )
        return response
    except Exception as e:
        print(f"Error fetching Cost Explorer data: {e}")
        print("Make sure the IAM role has ce:GetCostAndUsage permission and Cost Explorer is enabled.")
        sys.exit(1)


def main():
    ce = boto3.client('ce')

    end = datetime.utcnow().date()
    start = end - timedelta(days=7)

    print(f"# FinOps Cost Report")
    print(f"**Period:** {start} → {end}")
    print(f"**Generated:** {datetime.utcnow().isoformat()}Z\n")

    response = get_cost_and_usage(ce, start.isoformat(), end.isoformat())

    service_totals = defaultdict(float)
    gpu_related = 0.0
    total = 0.0

    for result in response.get('ResultsByTime', []):
        for group in result.get('Groups', []):
            keys = group['Keys']
            service = keys[0]
            usage_type = keys[1]
            amount = float(group['Metrics']['UnblendedCost']['Amount'])

            service_totals[service] += amount
            total += amount

            # Rough heuristic for GPU-related spend
            if any(x in usage_type.upper() for x in ['GPU', 'G4DN', 'G5', 'P3', 'P4', 'P5', 'INF1', 'TRN1']):
                gpu_related += amount

    print("## Cost by Service (last 7 days)\n")
    print("| Service | Cost (USD) |")
    print("|---------|------------|")
    for service, cost in sorted(service_totals.items(), key=lambda x: x[1], reverse=True):
        if cost > 0.01:
            print(f"| {service} | ${cost:.2f} |")

    print(f"\n**Total (7 days):** ${total:.2f}")
    print(f"**Estimated GPU-related:** ${gpu_related:.2f}\n")

    print("## Recommendations\n")
    if total < 1:
        print("- Costs are currently very low (good for learning phase).")
    if gpu_related > 0:
        print("- GPU spend detected. Review if training jobs are still running.")
        print("- Consider using Spot instances or smaller GPU types (g4dn) for non-critical workloads.")
    print("- Always run `terraform destroy` when the cluster is not needed.")
    print("- Enable AWS Budgets alerts for this account/project.")
    print("- Tag all resources with Project=gpu-ml-platform for better cost allocation.")

    print("\n---\n*Report generated by automation/finops/cost_report.py*")


if __name__ == "__main__":
    main()
